### PR TITLE
Bump DNSControl to v3.30.0

### PR DESCRIPTION
**Pull request by admdly**
https://github.com/StackExchange/dnscontrol/releases/tag/v3.30.0

### CODE REVIEW

**Comment by supercoffee** [comment]
@koenrh Can we get this update merged?

**Review by tlimoncelli — APPROVED** [review]

**Comment by flz** [comment]
Hey @koenrh, can we get this merged?

**Comment by admdly** [comment]
#99 opened to bump to latest release, but I'll leave this here for now as any update being merged would be great.

**Comment by tlimoncelli** [comment]
There is going to be a .1 release due to a bug in the BIND driver.  You should skip the .0 release this time.

**Comment by admdly** [comment]
> There is going to be a .1 release due to a bug in the BIND driver. You should skip the .0 release this time.

Noted, I've closed #99  and will create a new PR for the .1 release once available. I'll still leave this this for now, as I presume the v3.30.x branch is unaffected?

**Comment by tlimoncelli** [comment]
Yes. The v3.30.0 branch is fine for use.  Thanks for checking!

**Comment by admdly** [comment]
#101 opened to bump to latest release, but I'll also leave this for now as any update would be great.

**Comment by koenrh** [comment]
Apologies for the delay!

https://github.com/koenrh/dnscontrol-action/pull/101

**Pull request closed without merging**
