### PR TITLE
Add support for non-default DNSControl config file location 

### PR DESCRIPTION
**Pull request by koenrh**
Based on @markdorison's work in https://github.com/koenrh/dnscontrol-action/pull/37.

I made some minor changes to also make it work for current configurations where the path to the config or credentials file is not specified. In which case it should default to `dnsconfig.js` and `creds.json` in the current directory.

The working directory is always the directory containing the `dnsconfig.json`.

Tested the following cases:
* `dnsconfig.js` and `creds.json` in the current directory, `config_file` and `creds_file` arguments not specified.
* `dnsconfig.js` and `creds.json` in the directory `dns/`, config_file` and `creds_file` arguments specified (`dns/dnsconfig.js` and `dns/creds.json`, respectively)
* `dnsconfig.js` and `creds.json` in different directories, config_file` and `creds_file` arguments specified

### CODE REVIEW

**Comment by markdorison** [comment]
@koenrh thanks for pushing this forward! In my testing the `check` command is failing unexpectedly but I don't see a detailed error message. The `preview` command is working as expected.

I am running the action with this configuration:

```yaml
      - name: DNSControl check
        uses: koenrh/dnscontrol-action@support-non-default-config-path
        with:
          args: check
          config_file: path/dnsconfig.js
          creds_file: path/creds.json
```

**Comment by koenrh** [comment]
@markdorison I believe that is because the `check` sub-command doesn't need recognize the `--creds` flag. Which makes sense I guess because you don't need credentials to locally validate the config. Let me push a commit to fix this.

**Comment by koenrh** [comment]
3ab26ada343191b044927dfd7e7fe7d438b400f8 fixed the issue with the `check` sub-command.

**Review by markdorison — APPROVED** [review]
This is working as described!

**Pull request merged**
